### ISSUE TITLE
Spyloan malware on GmsCore.apk

### ISSUE THREAD

**Issue by azertylr** [MindTheGapps/14.0.0-arm64#10]
Hello,

ESET-NOD32 detected Android/SpyLoan.XK  on GmsCore.apk https://www.virustotal.com/gui/file/dfca71b10a2d5c99a36fb7b15436f2e6b529a439caf500aa7ff855bfa1aaa0a8?nocache=1

Is it normal?

Best

**Comment by luk1337** [comment]
false positive.
