### ISSUE TITLE
VirusTotal: Avast-Mobile reports infected with a trojan

### ISSUE THREAD

**Issue by eelcohn** [MindTheGapps/14.0.0-arm64#5]
Hi,

VirusTotal reports 1 hit on the `MindTheGapps-14.0.0-arm64-20240225_232108.zip` file:
https://www.virustotal.com/gui/file/c9473cc47c586165ddb28ce620e6a9f20f14c38a9d944cba26f2ca562f9b1537

Is this a false-positive?

![afbeelding](https://github.com/MindTheGapps/14.0.0-arm64/assets/17127588/55965e78-9074-4510-b7dd-9bc1db8b21dc)

**Comment by luk1337** [comment]
Yes.
