### ISSUE TITLE
[Feature Request]: Signed build variants

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [MindTheGapps/14.0.0-arm64#8]
Please If are possible please use same signatures from lineageOS for allows us to had signed builded system, is can be good in devices like
oneplus or google that can be locked with avb keys signed and all components full signed.

Why bootloader lock: 
TEE and keymaster support that are essential for cryptography and security apps.

Sorry if is not possible or is out of scope.
thank you

**Comment by npjohnson** [comment]
No, we aren't LineageOS, nor are we affiliated.

Not one of the developers here has access to those keys.

**Comment by npjohnson** [comment]
Additionally dude you are super confused over how signatures work, signing the zip has nothing to do with locking your bootloader. 

You need to sign your overall builds and include these in line, what you can absolutely do in its current state.

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> Additionally dude you are super confused over how signatures work, signing the zip has nothing to do with locking your bootloader.
> 
> You need to sign your overall builds and include these in line, what you can absolutely do in its current state.

oh thank you, this means that i can getting mindthegapps and build it signing with it just copying how divestos generate avb custom keys and signs?

**Comment by npjohnson** [comment]
None of what you said makes sense together. 

You can build mind the gaps into your build, not flash them after the fact, and then generate an AVB custom key and sign just as you would normally.
